# Memory and Java settings
org.gradle.jvmargs=-Xmx3G
org.gradle.java.home=C:/Users/Benicio/AppData/Roaming/.minecraft/runtime/java-runtime-gamma/windows/java-runtime-gamma

# Fabric Properties
minecraft_version=1.20.4
yarn_mappings=1.20.4+build.3
loader_version=0.15.11

# Mod Properties
mod_version=1.0.0
maven_group=com.isaacmod
archives_base_name=isaac_roguelike

# Dependencies
fabric_version=0.97.0+1.20.4
